### ISSUE TITLE
Non-working

### ISSUE THREAD

**Issue by zQueal** [donatj/PHP-Minecraft-Bukkit-Server-Status#1]
Just thought you might like to know, this plugin is no longer working correctly.

**Comment by donatj** [comment]
Works fine for me, you do need to Yaml extension to PHP installed though which does not come with it by default

**Comment by donatj** [comment]
Also, its not a plugin for bukkit server, if thats what you assumed, you need A web server light Apache or lighttpd set up as well as PHP with the Yaml extension

**Comment by zQueal** [comment]
Of course I've used the socratic method to figure out the problems. YAML is compiled and installed, also working correctly. An yea, I understand the infinite complexities of differences between a Minecraft plugin and a web-script.

**Comment by donatj** [comment]
Do you have the bukkit essentials pluggin installed?
On Apr 26, 2012 7:31 PM, "Xanza" <
reply@reply.github.com>
wrote:

**Comment by zQueal** [comment]
Yuuup.
